IAM-1247 Update sso-dashboard python runtime
mozilla-iam/sso-dashboard pull request #491
Opened 2024-02-12 16:04 UTC by frosemond

- Updated Dockerfile to use 3.12-bullseye
- Cleaned up requirements.txt file - removed secondary dependencies
- annotated requirements.txt file to

2024-02-23 16:59 UTC, dividehex requested changes
Looks good but lets pin _**all**_ the packages to ensure repeatable builds.

2024-02-23 16:59 UTC, dividehex commented on requirements.txt
I like how clean this is by only using the primary required libs and not including the deps, but this might lead to a problem in the future when deps get upgraded and they are not actually fully pinned.  You may build it one day and it works, but then build it another day and it break because a dep lib was update and either is incompatible or introduces a bug.  Can we just pin all the libs plus their deps?  `pip freeze > requirements.txt` is easy way to ensure all the packages get pinned.

2024-04-02 20:04 UTC, frosemond commented on requirements.txt
updated

2024-04-03 16:59 UTC, dividehex approved these changes
💯

2024-04-03 16:59 UTC, merged